(()=>{
const nav=document.querySelector('.navigation');
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.open=false));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('.project-drawer')?.open){nav.open=false;nav.querySelector('summary').focus()}});
const magic=document.querySelector('.magic');
magic.addEventListener('click',()=>{const enabled=document.querySelector('.biography').classList.toggle('magic-on');magic.setAttribute('aria-pressed',String(enabled));magic.textContent=enabled?'A little less magic':'Tap to see some magic'});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});
document.querySelectorAll('.project-panel,.quote,.section-intro').forEach(e=>{e.classList.add('reveal');observer.observe(e)});
document.documentElement.classList.add('js-motion');
}
})();

(()=>{const projects=[{"id": "bizinc", "name": "Bizinc", "category": "Marketplace & booking", "role": "Product Designer \u2192 UI/UX Manager", "date": "Apr 2024 \u2014 May 2026", "image": "bizinc", "original": "bizinc-home.jpg", "url": "https://www.bizinc.io", "label": "Visit Bizinc", "intro": "Helping people discover local businesses and book services, while giving business owners a clearer way to manage and grow.", "items": ["Mapped customer and business-owner journeys, from signup to discovery and booking.", "Designed marketplace, business profiles, bookings and operator dashboards.", "Built a shared component library and organised design files for developer handoff."], "scope": "Two-sided marketplace \u00b7 Booking journeys \u00b7 Design system", "result": "Company-reported results during the redesign period included 45% higher dashboard activation and 23% more customers. These are aggregate business figures, not isolated measures of my design contribution."}, {"id": "vista-itss", "name": "Vista Digital Banking", "category": "Banking & fintech", "role": "UI/UX Designer & Front-End Developer \u00b7 ITSS", "date": "May 2022 \u2014 Apr 2024", "image": "vista", "original": "vista-devices.jpg", "url": "https://vistabankgroup.com/", "label": "Visit Vista Bank", "intro": "Making retail and corporate banking easier to navigate across four West African markets.", "items": ["Designed onboarding, identity verification, account dashboards and transfer flows.", "Worked through corporate approval mandates, payments and secure messaging.", "Created reusable patterns for English and French experiences, and supported HTML/CSS implementation reviews."], "scope": "4 markets \u00b7 Retail & corporate banking \u00b7 2 languages", "result": "Recognised with ITSS\u2019s Outstanding Intern of the Year award for work associated with the Vista programme."}, {"id": "kremor-ai", "name": "Kremor AI", "category": "AI & commerce", "role": "UI/UX Designer \u00b7 Design & Research Lead", "date": "Jun 2024 \u2014 Jul 2026 \u00b7 Part-time contract", "image": "kremor", "original": "kremor-hero.jpg", "url": "https://kremor-ai-clone.vercel.app/", "label": "Open project demo", "intro": "Connecting AI-assisted African fashion creation with shopping and the workshop operations needed to make it real.", "items": ["Designed the customer storefront, AI creative workspace and operations dashboard.", "Added prompt guidance, quick actions and history to help people get started with AI creation.", "Mapped orders, measurements, artisan workflows and permissions across five staff roles."], "scope": "3 product surfaces \u00b7 5 staff roles \u00b7 Shared design system", "result": "Delivered connected experiences and developer-ready design handoff across the storefront, creative workspace and admin tools. The linked site is the project demo from my existing portfolio."}];const drawer=document.querySelector('.project-drawer');let opener;let oldOverflow='';
function close(){drawer.close()}
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects.find(p=>p.id===button.dataset.project);opener=button;
drawer.querySelector('.drawer-content').innerHTML=`<p class="drawer-kicker">${p.category}</p><h2 id="preview-title">${p.name}</h2><p class="drawer-intro">${p.intro}</p><dl class="drawer-facts"><div><dt>My role</dt><dd>${p.role}</dd></div><div><dt>Timeline</dt><dd>${p.date}</dd></div></dl><figure class="drawer-image"><img src="/projects/${p.original}" alt="Original ${p.name} project presentation"><figcaption>From the original project portfolio</figcaption></figure><h3>What I did</h3><ul>${p.items.map(i=>`<li>${i}</li>`).join('')}</ul><h3>Scope & delivery</h3><p>${p.scope}</p><p>${p.result}</p><div class="drawer-links"><a class="button primary" href="/work/${p.id}/">Full case study ↗</a><a class="button" href="${p.url}" target="_blank" rel="noopener noreferrer">${p.label} ↗</a></div>`;
oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';drawer.showModal();drawer.scrollTop=0;drawer.querySelector('.drawer-close').focus();}));
drawer.querySelector('.drawer-close').addEventListener('click',close);drawer.addEventListener('click',e=>{if(e.target===drawer){const r=drawer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});drawer.addEventListener('close',()=>{document.body.style.overflow=oldOverflow;opener?.focus()});})();
