(()=>{
const launcher=document.createElement('button');launcher.className='portfolio-search-launch';launcher.textContent='Ask about Jamiu';launcher.setAttribute('aria-haspopup','dialog');document.body.append(launcher);
const dialog=document.createElement('dialog');dialog.className='portfolio-search';dialog.setAttribute('aria-labelledby','portfolio-search-title');
dialog.innerHTML=`<header class="search-heading"><div><span class="search-kicker">A shortcut to the work</span><h2 id="portfolio-search-title">What would you like to know?</h2></div><button type="button" class="search-close" aria-label="Close portfolio search">Close</button></header><p class="search-mode">Portfolio search · Answers from published work, without generative AI.</p><div class="search-conversation" aria-live="polite" aria-relevant="additions"><p class="search-welcome">Explore Jamiu’s experience, design decisions and project examples. Choose a question or ask your own.</p></div><div class="search-suggestions"><button>Show me fintech work</button><button>What did you do at Bizinc?</button><button>Show me branding</button><button>Experience and skills</button></div><form class="search-form"><label for="portfolio-question">Ask a question</label><div><input id="portfolio-question" type="search" maxlength="400" placeholder="e.g. How do you approach design systems?" autocomplete="off" required><button type="submit">Explore</button></div></form>`;document.body.append(dialog);
const conversation=dialog.querySelector('.search-conversation'),input=dialog.querySelector('input'),form=dialog.querySelector('form');let records,loading,lastProject;
function text(tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el}
const stop=new Set('a an the i you your me my what how did do does is are was were at in on to of and for about show tell can has have with it work project projects please'.split(' '));
const groups=[['fintech','banking','bank','finance','financial','payments','payment','currency','currencies','loans','investment'],['branding','brand','logo','logos','identity','merchandise'],['skills','experience','career','background','education','about','cv','resume'],['research','testing','test','usability','discovery','findings'],['systems','system','components','component','tokens','library'],['ai','generative','artificial','intelligence'],['contact','email','hire','availability','available','pricing','sponsorship']];
function tokens(q){return q.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(t=>t.length>1&&!stop.has(t))}
function rank(q){let words=tokens(q),expanded=new Set(words);groups.forEach(g=>{if(g.some(w=>words.includes(w)))g.forEach(w=>expanded.add(w))});let matches=records.map(r=>{const title=r.title.toLowerCase(),body=(r.summary+' '+r.text).toLowerCase();let score=0;words.forEach(w=>{if(title.includes(w))score+=15});expanded.forEach(w=>{if(new RegExp('\\b'+w+'\\b','i').test(body))score+=words.includes(w)?3:1});if(words.some(w=>['cv','resume'].includes(w))&&r.id==='cv')score+=35;if(words.some(w=>['contact','email','hire','availability','available','pricing','sponsorship','experience','skills','education'].includes(w))&&r.id==='about')score+=25;if(words.some(w=>['branding','logos','logo','identity'].includes(w))&&r.id==='logos')score+=25;return {r,score}}).filter(v=>v.score>0).sort((a,b)=>b.score-a.score);if(!words.length&&lastProject)matches=[{r:lastProject,score:1}];return matches.slice(0,3).map(v=>v.r)}
function excerpt(r,q){const words=tokens(q);const chunks=r.text.split(/\n/).filter(Boolean);const chosen=chunks.map((s,i)=>({s,i,score:words.reduce((n,w)=>n+(s.toLowerCase().includes(w)?1:0),0)+(/what did|contribut|role|own|responsib/i.test(q)&&/what i owned/i.test(s)?10:0)})).sort((a,b)=>b.score-a.score||a.i-b.i)[0]?.s||r.summary;const clean=chosen.replace(/^\d+\s+[^:]+:\s*/,'');if(clean.length<=620)return clean;const end=clean.slice(0,620).lastIndexOf('. ');return clean.slice(0,end>200?end+1:600)+(end>200?'':'…')}
async function getRecords(){if(records)return records;if(!loading)loading=fetch('/portfolio-knowledge.json?v=1').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>records=data).catch(e=>{loading=null;throw e});return loading}
async function ask(q){q=q.trim();if(!q)return;form.querySelector('button').disabled=true;conversation.append(text('p',q,'search-question'));const response=text('div','','search-answer');response.append(text('p','Finding relevant work…'));conversation.append(response);input.value='';try{await getRecords();const found=rank(q);response.replaceChildren();response.append(text('p',found.length?excerpt(found[0],q):'I couldn’t find a clear match in the published portfolio. Try a project name, banking, branding, design systems, or experience. For details that aren’t published, contact Jamiu directly.'));if(found.length){lastProject=found[0];response.append(text('span','Explore the source','search-kicker'));const cards=text('div','','search-results');found.forEach(r=>{const a=document.createElement('a');a.href=r.url;a.className='search-result';if(r.image){const img=document.createElement('img');img.src=r.image;img.alt='';img.loading='lazy';a.append(img)}else{a.append(text('span',r.title.slice(0,1),'search-monogram'))}const copy=text('div');copy.append(text('strong',r.title),text('span',r.summary));a.append(copy);cards.append(a)});response.append(cards)}}catch{response.replaceChildren(text('p','Portfolio search could not load. Please try again, or browse selected work from the menu.'))}finally{form.querySelector('button').disabled=false;conversation.scrollTop=response.offsetTop-conversation.offsetTop}}
launcher.addEventListener('click',()=>{dialog.showModal();getRecords().catch(()=>{});input.focus()});dialog.querySelector('.search-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>launcher.focus());form.addEventListener('submit',e=>{e.preventDefault();ask(input.value)});dialog.querySelectorAll('.search-suggestions button').forEach(b=>b.addEventListener('click',()=>ask(b.textContent)));
})();
